environment:
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PATH%"
  - "pip install pyctdev && doit ecosystem_setup"
  - "doit develop_install -o examples -o tests"
  - "doit env_capture"

build: off

test_script:
  - "doit test_all"
